2023-03-25 12:25:11 ERROR    221 Connection lost. Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion.
]
2023-03-25 12:25:11 INFO     221 Reconnecting after 10 seconds ...
2023-03-25 12:25:21 INFO     221 Connecting to IPv4Address(type='TCP', host='127.0.0.1', port=5672) ...
2023-03-25 12:25:21 ERROR    221 Connection failed. Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionRefusedError'>: Connection was refused by other side: 111: Connection refused.
]
2023-03-25 12:25:21 INFO     221 Reconnecting after 10 seconds ...
2023-03-25 12:25:32 INFO     221 Connecting to IPv4Address(type='TCP', host='127.0.0.1', port=5672) ...
2023-03-25 12:25:32 INFO     221 Connection made to 127.0.0.1:5672
2023-03-25 12:25:32 INFO     221 Successfull authentication
2023-03-25 12:25:32 INFO     221 Got channel
2023-03-25 12:25:32 INFO     221 The channel is open
2023-03-25 12:25:32 ERROR    221 Channel open failed: [Failure instance: Traceback: <class 'twisted.internet.defer.AlreadyCalledError'>: 
/usr/lib/python3/dist-packages/twisted/internet/defer.py:1750:gotResult
/usr/lib/python3/dist-packages/twisted/internet/defer.py:1737:_inlineCallbacks
/usr/lib/python3/dist-packages/twisted/internet/defer.py:661:callback
/usr/lib/python3/dist-packages/twisted/internet/defer.py:763:_startRunCallbacks
--- <exception caught here> ---
/usr/lib/python3/dist-packages/twisted/internet/defer.py:857:_runCallbacks
/usr/local/lib/python3.10/dist-packages/jasmin/queues/factory.py:181:_channel_open
/usr/lib/python3/dist-packages/twisted/internet/defer.py:661:callback
/usr/lib/python3/dist-packages/twisted/internet/defer.py:756:_startRunCallbacks
]
2023-03-25 12:26:51 ERROR    221 Connection lost. Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion: Connection lost.
]
2023-03-25 12:26:51 INFO     221 Reconnecting after 10 seconds ...
2023-03-25 12:27:07 INFO     235 Connecting to IPv4Address(type='TCP', host='127.0.0.1', port=5672) ...
2023-03-25 12:27:07 ERROR    235 Connection failed. Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionRefusedError'>: Connection was refused by other side: 111: Connection refused.
]
2023-03-25 12:27:07 INFO     235 Reconnecting after 10 seconds ...
2023-03-25 12:27:08 INFO     234 Connecting to IPv4Address(type='TCP', host='127.0.0.1', port=5672) ...
2023-03-25 12:27:08 ERROR    234 Connection failed. Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionRefusedError'>: Connection was refused by other side: 111: Connection refused.
]
2023-03-25 12:27:08 INFO     234 Reconnecting after 10 seconds ...
2023-03-25 12:27:08 INFO     233 Connecting to IPv4Address(type='TCP', host='127.0.0.1', port=5672) ...
2023-03-25 12:27:08 ERROR    233 Connection failed. Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionRefusedError'>: Connection was refused by other side: 111: Connection refused.
]
2023-03-25 12:27:08 INFO     233 Reconnecting after 10 seconds ...
2023-03-25 12:27:17 INFO     235 Connecting to IPv4Address(type='TCP', host='127.0.0.1', port=5672) ...
2023-03-25 12:27:18 INFO     235 Connection made to 127.0.0.1:5672
2023-03-25 12:27:18 INFO     235 Successfull authentication
2023-03-25 12:27:18 INFO     235 Got channel
2023-03-25 12:27:18 INFO     235 The channel is open
2023-03-25 12:27:18 INFO     234 Connecting to IPv4Address(type='TCP', host='127.0.0.1', port=5672) ...
2023-03-25 12:27:18 INFO     235 A new queue has been successfully declared [DLRLookup-dlrlookupd-01]
2023-03-25 12:27:18 INFO     234 Connection made to 127.0.0.1:5672
2023-03-25 12:27:18 INFO     234 Successfull authentication
2023-03-25 12:27:18 INFO     234 Got channel
2023-03-25 12:27:18 INFO     234 The channel is open
2023-03-25 12:27:18 INFO     234 A new queue has been successfully declared [dlr_thrower]
2023-03-25 12:27:18 INFO     233 Connecting to IPv4Address(type='TCP', host='127.0.0.1', port=5672) ...
2023-03-25 12:27:18 INFO     233 Connection made to 127.0.0.1:5672
2023-03-25 12:27:18 INFO     233 Successfull authentication
2023-03-25 12:27:18 INFO     233 Got channel
2023-03-25 12:27:18 INFO     233 The channel is open
2023-03-25 12:27:18 INFO     233 A new queue has been successfully declared [RouterPB_deliver_sm_all]
2023-03-25 12:27:18 INFO     233 A new queue has been successfully declared [RouterPB_bill_request_submit_sm_resp_all]
2023-03-25 12:27:18 INFO     233 A new queue has been successfully declared [deliver_sm_thrower]
2023-03-25 12:27:18 INFO     233 A new queue has been successfully declared [submit.sm.testserver]
2023-03-25 12:27:18 INFO     233 A new queue has been successfully declared [submit.sm.testeProvider2]
